default: &default 
  adapter: postgresql 
  username: usuario 
  password: 186425 
  host: localhost 

development: 
  <<: *default 
  database: app_name_development 

test:
  <<: *default 
  database: app_name_test 

production: 
  <<: *default 
  database: app_name_production
