# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a178f6c903cc2019a7719dc3a0c79a033e8bb84e0d060a3f5a3a66cb7c011c2aef8cc5d956b8520f91b390ae964c75bf36e93d9be330904c0cdead74b819d3b

test:
  secret_key_base: edfdf37342c77f4699e36a28a5cdb262afedc79287a1a56c712f987d84a66c57325aea8716ad0c6df7e5cb9b71413689c77333ffd63eb8f9598c7c129ed08cd0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
